const API='';let token='';let lastNodes=[];const $=id=>document.getElementById(id);const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);function hex(bytes){const a=new Uint8Array(bytes);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}function traceparent(){return `00-${hex(16)}-${hex(8)}-01`}const headers=()=>{const h={traceparent:traceparent()};if(token)h.Authorization=`Bearer ${token}`;return h};
const titles={overview:'Command Center',operations:'Enterprise Operations',agent:'Autonomous Agent',approvals:'Governance Queue',traces:'Execution Traces',audit:'Audit & Assurance',architecture:'Architecture'};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));$(b.dataset.view).classList.add('active');b.classList.add('active');$('title').textContent=titles[b.dataset.view];});document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>{$('request').value=b.dataset.cmd});
async function get(path){const r=await fetch(API+path,{headers:headers()});if(!r.ok)throw new Error(await r.text());return r.json()}async function post(path,body){const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify(body||{})});if(!r.ok)throw new Error(await r.text());return r.json()}
function setIdentityStatus(message,ok=false){const el=$('identityNotice');if(!el)return;el.textContent=message;el.className=`identity-notice${ok?' ok':''}`}
function clearIdentity(){token='';if(aborter)aborter.abort();$('identityState').textContent='unsigned';setIdentityStatus('Select a tenant and role, then explicitly issue a signed demo identity.');$('identityBtn').textContent='Issue signed demo identity';$('identityBtn').disabled=false}
async function identity(){const btn=$('identityBtn'),role=$('role').value,tenant=$('tenant').value;btn.disabled=true;btn.textContent='Issuing signed identity…';setIdentityStatus('Requesting signed JWT from the Aurelian control plane…');try{const r=await fetch(`${API}/api/auth/demo-token?role=${encodeURIComponent(role)}&tenant_id=${encodeURIComponent(tenant)}&mfa=true`,{headers:{traceparent:traceparent()}});if(!r.ok)throw new Error(await r.text());const d=await r.json();token=d.access_token;$('identityState').textContent=`${tenant} · ${role} · ${d.mfa?'MFA':'NO MFA'}`;setIdentityStatus(`SIGNED · ${role.toUpperCase()} · ${tenant} · MFA ${d.mfa?'VERIFIED':'OFF'}`,true);btn.textContent='Identity issued ✓';await refresh();stream();setTimeout(()=>{btn.textContent='Reissue signed demo identity';btn.disabled=false},1200)}catch(e){token='';$('identityState').textContent='unsigned';setIdentityStatus(`ISSUE FAILED · ${e.message}`);btn.textContent='Issue signed demo identity';btn.disabled=false}}
$('identityBtn').onclick=identity;$('tenant').onchange=clearIdentity;$('role').onchange=clearIdentity;
async function overview(){const d=await get('/api/overview');$('revenue').textContent=money(d.kpis.booked_revenue);$('openValue').textContent=money(d.kpis.open_order_value);$('inventoryRisks').textContent=d.kpis.inventory_risks;$('pending').textContent=d.kpis.pending_approvals;$('auditState').textContent=d.kpis.audit_integrity?'VERIFIED':'FAILED';$('auditState').style.color=d.kpis.audit_integrity?'var(--green)':'var(--red)'}
async function operations(){const [p,o]=await Promise.all([get('/api/products'),get('/api/orders')]);$('products').innerHTML=p.products.map(x=>`<div class="product"><small>${x.sku} · ${x.category}</small><b>${x.name}</b><div class="price">${money(x.price)}</div><small class="${x.stock<=x.reorder_point?'risk':''}">${x.stock} in stock · reorder ${x.reorder_point} · ${x.margin_pct}% margin</small></div>`).join('');$('orders').innerHTML=`<table><thead><tr><th>ORDER</th><th>CUSTOMER</th><th>SKU</th><th>VALUE</th><th>STATE</th></tr></thead><tbody>${o.orders.map(x=>`<tr><td>${x.order_code}</td><td>${x.customer_code}</td><td>${x.sku}</td><td>${money(x.total)}</td><td>${x.status}</td></tr>`).join('')}</tbody></table>`}
async function approvals(){const d=await get('/api/approvals');$('approvalList').innerHTML=d.approvals.length?d.approvals.map(a=>`<div class="approval"><div class="tier">${a.approval_tier.toUpperCase()} · ${a.tool_name}</div><h3>Approval #${a.id}</h3><p>${a.reason}</p><pre>${a.args_json}</pre><button onclick="approve(${a.id})">Approve with current identity</button> <button onclick="deny(${a.id})">Deny</button></div>`).join(''):'<div class="panel">Queue clear. No governed actions await review.</div>'}window.approve=async id=>{try{await post(`/api/approvals/${id}/approve`,{note:'Approved after human review in public demonstration.'});await refresh()}catch(e){alert(e.message)}};window.deny=async id=>{try{await post(`/api/approvals/${id}/deny`,{note:'Denied after human review.'});await refresh()}catch(e){alert(e.message)}};
function renderGraph(nodes){lastNodes=nodes.slice(-12);$('stateGraph').innerHTML=lastNodes.map((n,i)=>`<div class="node ${i===lastNodes.length-1?'active':''}"><b>${n.node}</b><small>attempt ${n.attempt||1}<br>${Math.round(n.latency_ms||0)} ms</small></div>`).join('')}
async function traces(){const d=await get('/api/traces');$('otel').textContent=d.telemetry.otlp_enabled?'EXPORTING':'LOCAL';const rows=d.traces.slice().reverse();renderGraph(rows);$('traceTable').innerHTML=`<table><thead><tr><th>TASK</th><th>NODE</th><th>ATTEMPT</th><th>LATENCY</th></tr></thead><tbody>${d.traces.map(x=>`<tr><td>#${x.task_id}</td><td>${x.node}</td><td>${x.attempt}</td><td>${Math.round(x.latency_ms)} ms</td></tr>`).join('')}</tbody></table>`}
async function audit(){const d=await get('/api/audit?limit=35');$('auditEvents').innerHTML=d.events.map(e=>`<div class="audit-event"><b>${e.event_type}</b><small>${e.actor} · ${new Date(e.created_at).toLocaleTimeString()} · ${e.event_hash.slice(0,16)}… · sig ${e.signature.slice(0,10)}…</small></div>`).join('')}
$('verifyBtn').onclick=async()=>{const d=await get('/api/audit/verify');alert(d.valid?`Audit chain VALID · ${d.events} signed events`:`Audit chain FAILED at ${d.failed_id}`)};$('evalBtn').onclick=async()=>{const d=await get('/api/evals/run');$('evals').innerHTML=`<h2>${d.passed}/${d.total}</h2>`+d.checks.map(x=>`<p style="color:${x.passed?'var(--green)':'var(--red)'}">${x.passed?'PASS':'FAIL'} · ${x.name}</p>`).join('')}
$('runBtn').onclick=async()=>{const t=performance.now();$('result').textContent='Executing checkpointed workflow…';try{const d=await post('/api/tasks',{request:$('request').value});$('result').textContent=JSON.stringify(d,null,2);$('executionTimer').textContent=`${Math.round(performance.now()-t)} ms`;await refresh();if(d.status==='pending_approval'){document.querySelector('[data-view="approvals"]').click()}}catch(e){$('result').textContent=e.message}};
async function refresh(){if(!token)return;await Promise.all([overview(),operations(),approvals(),traces(),audit()])}
let aborter;async function stream(){if(aborter)aborter.abort();aborter=new AbortController();$('streamState').textContent='event stream live';try{const r=await fetch(API+'/api/events/stream',{headers:headers(),signal:aborter.signal});const reader=r.body.getReader(),decoder=new TextDecoder();let buf='';while(true){const {done,value}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const blocks=buf.split('\n\n');buf=blocks.pop();for(const block of blocks){const line=block.split('\n').find(x=>x.startsWith('data: '));if(!line)continue;const data=JSON.parse(line.slice(6));if(!data.type)continue;const div=document.createElement('div');div.className='event';div.innerHTML=`<b>${data.type}</b> · ${data.node||data.status||''}<br>${new Date().toLocaleTimeString()} · task ${data.task_id||'—'}`;$('eventLog').prepend(div);if(data.node){lastNodes.push(data);renderGraph(lastNodes)}}}}catch(e){if(e.name!=='AbortError')$('streamState').textContent='event stream reconnect required'}}
clearIdentity();
